import React, { useEffect, useState } from "react";
import { useApp } from "../AppContext";
import {
  TrendingUp,
  ArrowRight,
  Cpu,
  Shield,
  BrainCircuit,
  Award,
  Activity,
  BarChart3,
} from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { AnimatedMarketBackground } from "./AnimatedMarketBackground";
import { GlobalFinancialNetwork } from "./GlobalFinancialNetwork";

// ─────────────────────────────────────────────────────────────────────────────
//  Feature Cards
// ─────────────────────────────────────────────────────────────────────────────
const FEATURES = [
  {
    icon: Activity,
    title: "Virtual Trading",
    desc: "Buy and sell top Nifty 50 companies with ₹10,00,000 in virtual funds. Real-time price simulation, holding margins, instant feedback.",
    tag: "SIMULATOR",
    tagColor: "#3ecf8e",
  },
  {
    icon: BrainCircuit,
    title: "Learn with AI",
    desc: "Personalized educational notes generated by AI — tailored to your experience level, occupation, and learning objectives.",
    tag: "AI-POWERED",
    tagColor: "#4f6bff",
  },
  {
    icon: BarChart3,
    title: "Portfolio Analysis",
    desc: "Deep-dive analytics on your holdings — risk index, diversification coefficient, sector exposure, and AI-driven recommendations.",
    tag: "ANALYTICS",
    tagColor: "#8b93a7",
  },
  {
    icon: Award,
    title: "Progress Tracking",
    desc: "Adaptive AI quizzes on technical metrics, fundamental analysis, and trade strategies — with progress milestones you can earn.",
    tag: "LEARNING",
    tagColor: "#4f6bff",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
//  Floating Stock Widgets - Randomly distributed on the right side
// ─────────────────────────────────────────────────────────────────────────────
const HERO_MARKET_WIDGETS = [
  { symbol: "NIFTY 50", value: "+1.24%", top: "14%", left: "53%", delay: 0, tone: "#3ecf8e" },
  { symbol: "Reliance", value: "BUY", top: "42%", left: "84%", delay: 0.9, tone: "#3ecf8e" },
  { symbol: "Infosys", value: "Bearish", top: "74%", left: "8%", delay: 1.8, tone: "#f0576b" },
  { symbol: "AI Confidence", value: "94%", top: "26%", left: "70%", delay: 2.7, tone: "#4f6bff" },
  { symbol: "Market Sentiment", value: "Bullish", top: "66%", left: "60%", delay: 3.6, tone: "#3ecf8e" },
];

// ─────────────────────────────────────────────────────────────────────────────
//  Component
// ─────────────────────────────────────────────────────────────────────────────
export const LandingPage: React.FC = () => {
  const { setActiveView } = useApp();
  const [ctaClicking, setCtaClicking] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);
  const [mouseParallax, setMouseParallax] = useState({ x: 0, y: 0 });
  const reducedMotion = useReducedMotion();

  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 8);
    handleScroll();
    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const handleMouseMove = (e: React.MouseEvent) => {
    if (reducedMotion) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const x = (e.clientX - rect.left) / rect.width - 0.5; // -0.5 to 0.5
    const y = (e.clientY - rect.top) / rect.height - 0.5; // -0.5 to 0.5
    setMouseParallax({ x, y });
  };

  const handleMouseLeave = () => {
    setMouseParallax({ x: 0, y: 0 });
  };

  const handleStartLearning = () => {
    setCtaClicking(true);
    setTimeout(() => {
      setCtaClicking(false);
      setActiveView("register");
    }, 450);
  };

  return (
    <div
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      style={{
        minHeight: "100vh",
        background: "#070B14",
        color: "var(--color-trado-text)",
        overflowX: "hidden",
        position: "relative",
      }}
    >
      {/* ── Full-page fixed animated market background ── */}
      <AnimatedMarketBackground />

      {/* ── Floating Glass Navbar ─────────────────────────────────────────── */}
      <header
        style={{
          border: isScrolled ? "1px solid rgba(132, 164, 255, 0.16)" : "1px solid rgba(132, 164, 255, 0.08)",
          background: isScrolled ? "rgba(7, 11, 20, 0.82)" : "rgba(7, 11, 20, 0.45)",
          backdropFilter: isScrolled ? "blur(28px) saturate(135%)" : "blur(20px) saturate(125%)",
          WebkitBackdropFilter: isScrolled ? "blur(28px) saturate(135%)" : "blur(20px) saturate(125%)",
          position: "fixed",
          top: 24,
          left: 36,
          right: 36,
          zIndex: 999,
          borderRadius: 22,
          padding: "0 22px",
          transform: isScrolled ? "scale(0.96)" : "scale(1)",
          transformOrigin: "top center",
          boxShadow: isScrolled
            ? "0 18px 44px rgba(0,0,0,0.48), 0 0 30px rgba(79,107,255,0.18), inset 0 1px 0 rgba(255,255,255,0.06)"
            : "0 12px 34px rgba(0,0,0,0.26), 0 0 22px rgba(79,107,255,0.08), inset 0 1px 0 rgba(255,255,255,0.05)",
          transition: "background 300ms ease, box-shadow 300ms ease, border-color 300ms ease, transform 300ms ease, backdrop-filter 300ms ease",
        }}
      >
        <div
          style={{
            maxWidth: 1280,
            margin: "0 auto",
            height: 68,
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          {/* Logo */}
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div
              style={{
                height: 36,
                width: 36,
                borderRadius: 10,
                background: "linear-gradient(135deg, #4f6bff, #7a96ff)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                boxShadow: "0 8px 24px rgba(79,107,255,0.28)",
              }}
            >
              <TrendingUp size={17} color="#fff" strokeWidth={2.5} />
            </div>
            <span
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 700,
                fontSize: 21,
                letterSpacing: "-0.025em",
                color: "var(--color-trado-text)",
              }}
            >
              Trado
            </span>
          </div>

          {/* Nav actions */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <button
              onClick={() => setActiveView("signin")}
              style={{
                background: "transparent",
                border: "none",
                color: "var(--color-trado-muted)",
                fontSize: 13.5,
                fontWeight: 500,
                padding: "8px 16px",
                cursor: "pointer",
                borderRadius: 8,
                transition: "color 180ms ease",
                minHeight: 40,
              }}
              onMouseEnter={(e) =>
                ((e.currentTarget as HTMLButtonElement).style.color =
                  "var(--color-trado-text)")
              }
              onMouseLeave={(e) =>
                ((e.currentTarget as HTMLButtonElement).style.color =
                  "var(--color-trado-muted)")
              }
            >
              Sign In
            </button>
            <button
              onClick={() => setActiveView("register")}
              style={{
                background: "linear-gradient(135deg, #4f6bff, #6f8dff)",
                border: "1px solid rgba(255,255,255,0.1)",
                color: "#fff",
                fontSize: 13.5,
                fontWeight: 600,
                padding: "8px 20px",
                borderRadius: 999,
                cursor: "pointer",
                boxShadow: "0 8px 24px rgba(79,107,255,0.22)",
                transition: "transform 200ms ease, box-shadow 200ms ease",
                display: "flex",
                alignItems: "center",
                gap: 6,
                minHeight: 40,
              }}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.transform =
                  "translateY(-1px) scale(1.02)";
                (e.currentTarget as HTMLButtonElement).style.boxShadow =
                  "0 12px 28px rgba(79,107,255,0.3)";
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.transform =
                  "translateY(0) scale(1)";
                (e.currentTarget as HTMLButtonElement).style.boxShadow =
                  "0 8px 24px rgba(79,107,255,0.22)";
              }}
            >
              Get Started
              <ArrowRight size={14} />
            </button>
          </div>
        </div>
      </header>
      <div style={{ height: 92 }} />

      {/* ── Hero ───────────────────────────────────────────────────────────── */}
      <section
        style={{
          maxWidth: 1280,
          margin: "0 auto",
          padding: "100px 24px 120px",
          display: "flex",
          alignItems: "center",
          gap: 56,
          flexWrap: "wrap",
          position: "relative",
          zIndex: 10,
        }}
      >
        {/* Parallax Layer 4px: Floating Stock Widgets Overlay */}
        <motion.div
          aria-hidden="true"
          animate={reducedMotion ? undefined : { x: mouseParallax.x * 4, y: mouseParallax.y * 4 }}
          transition={{ type: "spring", stiffness: 85, damping: 24 }}
          style={{
            position: "absolute",
            inset: "-70px -18px -55px",
            pointerEvents: "none",
            overflow: "hidden",
            zIndex: 0,
          }}
        >
          {/* Subtle Ambient Volumetric Glow behind globe/widgets */}
          <motion.div
            animate={reducedMotion ? undefined : { x: [0, 26, -12, 0], y: [0, -18, 12, 0], scale: [1, 1.05, 1] }}
            transition={{ duration: 11, repeat: Infinity, ease: "easeInOut" }}
            style={{
              position: "absolute",
              left: "48%",
              top: "10%",
              width: "48%",
              height: "62%",
              borderRadius: "50%",
              background: "radial-gradient(circle, rgba(79,107,255,0.082), rgba(54,209,255,0.03) 45%, transparent 72%)",
              filter: "blur(52px)",
            }}
          />

          {HERO_MARKET_WIDGETS.map((widget, index) => (
            <motion.div
              key={widget.symbol}
              animate={
                reducedMotion
                  ? undefined
                  : {
                      x: [0, index % 2 === 0 ? 14 : -10, 0],
                      y: [0, index % 2 === 0 ? -16 : 13, 0],
                      rotate: [0, index % 2 === 0 ? 1.5 : -1.2, 0],
                    }
              }
              transition={{
                duration: 7.2 + index * 0.9,
                repeat: Infinity,
                ease: "easeInOut",
                delay: widget.delay,
              }}
              style={{
                position: "absolute",
                top: widget.top,
                left: widget.left,
                minWidth: 122,
                padding: "10px 14px",
                borderRadius: 12,
                background: "rgba(10, 16, 26, 0.45)",
                border: "1px solid rgba(175, 196, 255, 0.08)",
                boxShadow:
                  "0 14px 34px rgba(0,0,0,0.22), 0 0 24px rgba(79,107,255,0.08), inset 0 1px 0 rgba(255,255,255,0.04)",
                backdropFilter: "blur(18px)",
                WebkitBackdropFilter: "blur(18px)",
                opacity: 0.65,
              }}
            >
              <div
                style={{
                  fontFamily: "var(--font-mono)",
                  fontSize: 9.5,
                  letterSpacing: "0.08em",
                  color: "rgba(232,234,237,0.6)",
                }}
              >
                {widget.symbol}
              </div>
              <div
                style={{
                  marginTop: 4,
                  fontFamily: "var(--font-display)",
                  fontWeight: 700,
                  fontSize: 15,
                  color: widget.tone,
                  textShadow: `0 0 18px ${widget.tone}25`,
                }}
              >
                {widget.value}
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* ── Left Column: Hero Content with 1px/2px Parallax ── */}
        <motion.div
          animate={reducedMotion ? undefined : { x: mouseParallax.x * 1.0, y: mouseParallax.y * 1.0 }}
          transition={{ type: "spring", stiffness: 85, damping: 24 }}
          style={{ flex: "1 1 460px", minWidth: 280, position: "relative", zIndex: 3 }}
        >
          {/* Badge */}
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 7,
              padding: "6px 14px",
              borderRadius: 999,
              background: "rgba(79, 107, 255, 0.08)",
              border: "1px solid rgba(79, 107, 255, 0.2)",
              fontSize: 10.5,
              fontFamily: "var(--font-mono)",
              color: "#7fa3ff",
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              marginBottom: 28,
              boxShadow: "0 0 20px rgba(79,107,255,0.1)",
            }}
          >
            <Cpu size={11} />
            AI-Powered Virtual Trading
          </div>

          {/* Headline */}
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 700,
              fontSize: "clamp(36px, 5vw, 62px)",
              lineHeight: 1.06,
              letterSpacing: "-0.025em",
              color: "var(--color-trado-text)",
              marginBottom: 20,
            }}
          >
            Master the Markets
            <br />
            with{" "}
            <span
              style={{
                background: "linear-gradient(135deg, #AFC4FF 0%, #6D8CFF 52%, #36D1FF 100%)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
                backgroundClip: "text",
                filter: "drop-shadow(0 0 18px rgba(109,140,255,0.16))",
              }}
            >
              Virtual Capital
            </span>
          </h1>

          {/* Description */}
          <p
            style={{
              color: "var(--color-trado-muted)",
              fontSize: 17,
              lineHeight: 1.75,
              maxWidth: 470,
              margin: "0 0 36px",
            }}
          >
            Learn stock markets using{" "}
            <span style={{ color: "var(--color-trado-text)", fontWeight: 500 }}>
              ₹10,00,000 in virtual funds.
            </span>{" "}
            Practice investing. Build confidence. Receive AI-powered insights.
            Completely risk-free.
          </p>

          {/* CTA Buttons with 2px parallax */}
          <motion.div
            animate={reducedMotion ? undefined : { x: mouseParallax.x * 2.0, y: mouseParallax.y * 2.0 }}
            transition={{ type: "spring", stiffness: 85, damping: 24 }}
            style={{ display: "flex", gap: 14, flexWrap: "wrap" }}
          >
            <button
              onClick={handleStartLearning}
              className={ctaClicking ? "animate-glow-click" : ""}
              style={{
                background: "linear-gradient(135deg, #4f6bff, #6f8dff)",
                border: "1px solid rgba(255,255,255,0.1)",
                color: "#fff",
                fontSize: 14.5,
                fontWeight: 600,
                padding: "13px 28px",
                borderRadius: 999,
                cursor: "pointer",
                boxShadow:
                  "0 12px 30px rgba(79,107,255,0.22), 0 0 22px rgba(54,209,255,0.08)",
                transition: "transform 200ms ease, box-shadow 200ms ease",
                display: "flex",
                alignItems: "center",
                gap: 8,
                minHeight: 48,
              }}
              onMouseEnter={(e) => {
                if (!ctaClicking) {
                  (e.currentTarget as HTMLButtonElement).style.transform =
                    "translateY(-2px) scale(1.02)";
                  (e.currentTarget as HTMLButtonElement).style.boxShadow =
                    "0 16px 36px rgba(79,107,255,0.3), 0 0 28px rgba(54,209,255,0.12)";
                }
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.transform =
                  "translateY(0) scale(1)";
                (e.currentTarget as HTMLButtonElement).style.boxShadow =
                  "0 12px 30px rgba(79,107,255,0.22), 0 0 22px rgba(54,209,255,0.08)";
              }}
            >
              Start Learning
              <ArrowRight size={16} />
            </button>

            <button
              onClick={() =>
                document
                  .getElementById("features")
                  ?.scrollIntoView({ behavior: "smooth" })
              }
              style={{
                background: "rgba(255,255,255,0.03)",
                border: "1px solid rgba(255,255,255,0.07)",
                color: "var(--color-trado-muted)",
                fontSize: 14.5,
                fontWeight: 500,
                padding: "13px 28px",
                borderRadius: 999,
                cursor: "pointer",
                transition: "all 200ms ease",
                display: "flex",
                alignItems: "center",
                gap: 8,
                minHeight: 48,
              }}
              onMouseEnter={(e) => {
                const btn = e.currentTarget as HTMLButtonElement;
                btn.style.borderColor = "rgba(255,255,255,0.14)";
                btn.style.color = "var(--color-trado-text)";
                btn.style.background = "rgba(255,255,255,0.055)";
                btn.style.transform = "translateY(-1px)";
              }}
              onMouseLeave={(e) => {
                const btn = e.currentTarget as HTMLButtonElement;
                btn.style.borderColor = "rgba(255,255,255,0.07)";
                btn.style.color = "var(--color-trado-muted)";
                btn.style.background = "rgba(255,255,255,0.03)";
                btn.style.transform = "translateY(0)";
              }}
            >
              Explore Simulator
            </button>
          </motion.div>

          {/* Social proof row */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 20,
              marginTop: 36,
              paddingTop: 28,
              borderTop: "1px solid rgba(255,255,255,0.05)",
              flexWrap: "wrap",
            }}
          >
            {[
              { label: "Virtual Capital", value: "₹10L" },
              { label: "Nifty 50 Stocks", value: "50+" },
              { label: "AI Insights", value: "Real-time" },
            ].map((stat) => (
              <div key={stat.label}>
                <div
                  style={{
                    fontFamily: "var(--font-display)",
                    fontWeight: 700,
                    fontSize: 18,
                    color: "var(--color-trado-text)",
                    letterSpacing: "-0.02em",
                  }}
                >
                  {stat.value}
                </div>
                <div
                  style={{
                    fontSize: 11,
                    color: "var(--color-trado-muted)",
                    fontFamily: "var(--font-mono)",
                    marginTop: 2,
                  }}
                >
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* ── Right Column: World Network with 8px Parallax ── */}
        <motion.div
          animate={reducedMotion ? undefined : { x: mouseParallax.x * 8.0, y: mouseParallax.y * 8.0 }}
          transition={{ type: "spring", stiffness: 85, damping: 24 }}
          style={{
            flex: "1 1 500px",
            minWidth: 300,
            height: "460px",
            position: "relative",
            zIndex: 1,
          }}
        >
          <GlobalFinancialNetwork />
        </motion.div>
      </section>

      {/* ── Divider ─────────────────────────────────────────────────────────── */}
      <div
        style={{
          maxWidth: 1280,
          margin: "0 auto",
          padding: "0 24px",
          position: "relative",
          zIndex: 10,
        }}
      >
        <div style={{ height: 1, background: "rgba(255,255,255,0.04)" }} />
      </div>

      {/* ── Feature Cards ───────────────────────────────────────────────────── */}
      <section
        id="features"
        style={{
          maxWidth: 1280,
          margin: "0 auto",
          padding: "80px 24px 90px",
          position: "relative",
          zIndex: 10,
        }}
      >
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.45, ease: "easeOut" }}
          style={{ textAlign: "center", marginBottom: 52 }}
        >
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              padding: "5px 12px",
              borderRadius: 999,
              background: "rgba(79,107,255,0.07)",
              border: "1px solid rgba(79,107,255,0.15)",
              fontSize: 10,
              fontFamily: "var(--font-mono)",
              color: "#7fa3ff",
              letterSpacing: "0.1em",
              textTransform: "uppercase",
              marginBottom: 18,
            }}
          >
            Learn. Practice. Master.
          </div>
          <h2
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 700,
              fontSize: "clamp(24px, 3.5vw, 38px)",
              color: "var(--color-trado-text)",
              letterSpacing: "-0.02em",
              marginBottom: 14,
            }}
          >
            Designed for learners.
            <br />
            <span style={{ color: "var(--color-trado-muted)", fontWeight: 500 }}>
              Built for serious momentum.
            </span>
          </h2>
          <p
            style={{
              color: "var(--color-trado-muted)",
              maxWidth: 540,
              margin: "0 auto",
              lineHeight: 1.7,
              fontSize: 15.5,
            }}
          >
            A calm, intelligent trading environment with AI coaching,
            live-market context, and a simulator that feels polished enough for
            real-world practice.
          </p>
        </motion.div>

        {/* Card grid */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
            gap: 18,
          }}
        >
          {FEATURES.map((f, i) => {
            const Icon = f.icon;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.38, delay: i * 0.08, ease: "easeOut" }}
                whileHover={{ y: -5, transition: { duration: 0.22 } }}
                style={{
                  padding: "28px 26px",
                  borderRadius: 20,
                  background: "rgba(15, 20, 32, 0.7)",
                  backdropFilter: "blur(24px)",
                  WebkitBackdropFilter: "blur(24px)",
                  border: "1px solid rgba(255,255,255,0.06)",
                  boxShadow:
                    "0 4px 24px rgba(0,0,0,0.25), inset 0 1px 0 rgba(255,255,255,0.04)",
                  cursor: "default",
                  transition: "border-color 250ms ease, box-shadow 250ms ease",
                  position: "relative",
                  overflow: "hidden",
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget as HTMLDivElement;
                  el.style.borderColor = "rgba(79,107,255,0.2)";
                  el.style.boxShadow =
                    "0 12px 40px rgba(0,0,0,0.3), 0 0 0 1px rgba(79,107,255,0.1), inset 0 1px 0 rgba(255,255,255,0.06)";
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget as HTMLDivElement;
                  el.style.borderColor = "rgba(255,255,255,0.06)";
                  el.style.boxShadow =
                    "0 4px 24px rgba(0,0,0,0.25), inset 0 1px 0 rgba(255,255,255,0.04)";
                }}
              >
                {/* Corner accent glow */}
                <div
                  style={{
                    position: "absolute",
                    top: -40,
                    right: -40,
                    width: 120,
                    height: 120,
                    borderRadius: "50%",
                    background: `radial-gradient(circle, ${f.tagColor}18 0%, transparent 70%)`,
                    pointerEvents: "none",
                  }}
                />

                {/* Tag */}
                <div
                  style={{
                    display: "inline-flex",
                    alignItems: "center",
                    padding: "3px 8px",
                    borderRadius: 4,
                    background: `${f.tagColor}14`,
                    border: `1px solid ${f.tagColor}30`,
                    fontSize: 9,
                    fontFamily: "var(--font-mono)",
                    color: f.tagColor,
                    letterSpacing: "0.1em",
                    marginBottom: 20,
                  }}
                >
                  {f.tag}
                </div>

                {/* Icon */}
                <div
                  style={{
                    width: 44,
                    height: 44,
                    borderRadius: 12,
                    background: "rgba(79,107,255,0.1)",
                    border: "1px solid rgba(255,255,255,0.07)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "var(--color-trado-accent)",
                    marginBottom: 18,
                    boxShadow: "0 0 20px rgba(79,107,255,0.08)",
                  }}
                >
                  <Icon size={20} />
                </div>

                <h3
                  style={{
                    fontFamily: "var(--font-display)",
                    fontWeight: 600,
                    fontSize: 17,
                    color: "var(--color-trado-text)",
                    marginBottom: 10,
                    letterSpacing: "-0.01em",
                  }}
                >
                  {f.title}
                </h3>
                <p style={{ color: "var(--color-trado-muted)", fontSize: 13.5, lineHeight: 1.65 }}>
                  {f.desc}
                </p>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* ── CTA Section ────────────────────────────────────────────────────── */}
      <section
        style={{
          padding: "80px 24px",
          textAlign: "center",
          position: "relative",
          zIndex: 10,
          borderTop: "1px solid rgba(255,255,255,0.04)",
        }}
      >
        {/* Subtle background glow */}
        <div
          style={{
            position: "absolute",
            inset: 0,
            background: "radial-gradient(ellipse at 50% 50%, rgba(79,107,255,0.055) 0%, transparent 70%)",
            pointerEvents: "none",
          }}
        />

        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, ease: "easeOut" }}
          style={{ maxWidth: 620, margin: "0 auto", position: "relative" }}
        >
          {/* Icon */}
          <div
            style={{
              width: 52,
              height: 52,
              borderRadius: "50%",
              background: "rgba(79,107,255,0.1)",
              border: "1px solid rgba(255,255,255,0.07)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              margin: "0 auto 22px",
              color: "var(--color-trado-accent)",
              boxShadow: "0 0 32px rgba(79,107,255,0.12)",
            }}
          >
            <Shield size={22} />
          </div>

          <h2
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 700,
              fontSize: "clamp(22px, 3.5vw, 36px)",
              color: "var(--color-trado-text)",
              letterSpacing: "-0.02em",
              marginBottom: 16,
            }}
          >
            Zero financial risk.
            <br />
            True professional skill.
          </h2>

          <p
            style={{
              color: "var(--color-trado-muted)",
              lineHeight: 1.75,
              marginBottom: 34,
              fontSize: 15.5,
            }}
          >
            Trado is built solely for education. Every trade, portfolio stat,
            and AI signal is fully simulated — so you can sharpen your
            judgment without real capital at stake.
          </p>

          <button
            onClick={() => setActiveView("register")}
            style={{
              background: "linear-gradient(135deg, #4f6bff, #6f8dff)",
              border: "1px solid rgba(255,255,255,0.1)",
              color: "#fff",
              fontSize: 14.5,
              fontWeight: 600,
              padding: "13px 32px",
              borderRadius: 999,
              cursor: "pointer",
              boxShadow:
                "0 12px 30px rgba(79,107,255,0.22), 0 0 22px rgba(54,209,255,0.08)",
              display: "inline-flex",
              alignItems: "center",
              gap: 8,
              transition: "transform 200ms ease, box-shadow 200ms ease",
              minHeight: 48,
            }}
            onMouseEnter={(e) => {
              (e.currentTarget as HTMLButtonElement).style.transform =
                "translateY(-2px) scale(1.02)";
              (e.currentTarget as HTMLButtonElement).style.boxShadow =
                "0 16px 36px rgba(79,107,255,0.3), 0 0 28px rgba(54,209,255,0.12)";
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.transform =
                "translateY(0) scale(1)";
              (e.currentTarget as HTMLButtonElement).style.boxShadow =
                "0 12px 30px rgba(79,107,255,0.22), 0 0 22px rgba(54,209,255,0.08)";
            }}
          >
            Create Your Free Account
            <ArrowRight size={16} />
          </button>

          {/* Trust signal */}
          <p
            style={{
              marginTop: 18,
              fontSize: 12,
              color: "var(--color-trado-muted)",
              opacity: 0.6,
              fontFamily: "var(--font-mono)",
            }}
          >
            No credit card required · No real money · 100% educational
          </p>
        </motion.div>
      </section>

      {/* ── Footer ─────────────────────────────────────────────────────────── */}
      <footer
        style={{
          borderTop: "1px solid rgba(255,255,255,0.04)",
          background: "rgba(5, 8, 15, 0.85)",
          backdropFilter: "blur(16px)",
          WebkitBackdropFilter: "blur(16px)",
          padding: "24px",
          position: "relative",
          zIndex: 10,
        }}
      >
        <div
          style={{
            maxWidth: 1280,
            margin: "0 auto",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexWrap: "wrap",
            gap: 12,
          }}
        >
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div
              style={{
                height: 26,
                width: 26,
                borderRadius: 7,
                background: "linear-gradient(135deg, #4f6bff, #7a96ff)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <TrendingUp size={13} color="#fff" strokeWidth={2.5} />
            </div>
            <span
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 600,
                fontSize: 14,
                color: "var(--color-trado-muted)",
                letterSpacing: "-0.01em",
              }}
            >
              Trado
            </span>
          </div>

          <p style={{ color: "var(--color-trado-muted)", fontSize: 12, opacity: 0.55 }}>
            © {new Date().getFullYear()} Trado — Virtual Trading Platform. Built for education only.
          </p>

          <div style={{ display: "flex", gap: 18, flexWrap: "wrap" }}>
            {["Simulated Nifty 50", "AI-Powered Analytics", "No Real Money"].map((label) => (
              <span
                key={label}
                style={{
                  color: "var(--color-trado-muted)",
                  fontSize: 11,
                  fontFamily: "var(--font-mono)",
                  opacity: 0.45,
                }}
              >
                {label}
              </span>
            ))}
          </div>
        </div>
      </footer>
    </div>
  );
};
